name: ⚙️ Заявка на плагин ⚙️
title: '[Заявка на плагин] '
description: Подать заявку на создание плагина
labels: ['type: плагин']

body:
  - type: textarea
    id: project_name
    attributes:
      label: Название плагина
      description: Напишите название плагина
      placeholder: Название
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Описание плагина
      description: Напишите полное описание плагина
      placeholder: Описание
    validations:
      required: true

  - type: textarea
    id: author
    attributes:
      label: Юзернейм автора
      description: Напишите юзернейм автора плагина на GitHub
      placeholder: Автор
    validations:
      required: true

  - type: textarea
    id: release_eta
    attributes:
      label: Срок релиза
      description: Напишите ориентировочный срок релиза
      placeholder: Срок
    validations:
      required: true
